'use client';

import { useState, useMemo } from 'react';
import { useParams } from 'next/navigation';
import { useLoadingRouter as useRouter } from '@/hooks/useLoadingRouter';
import { DataTable, Column } from '@/components/organisms/shared/DataTable';
import { EndorsedReferencePill } from '@/components/atoms/EndorsedReferencePill';
import { DatePicker } from '@/components/atoms/DatePicker';
import { SearchSelect } from '@/components/atoms/SearchSelect';
import { MultiSelect } from '@/components/atoms/MultiSelect';
import {
  useCedantOptions,
  useReinsurerOptions,
  useCurrencyOptions,
  useClaimsReport,
} from '@/hooks';
import {
  ClaimReportRow,
  ClaimsReportBucket,
  ClaimsReportParams,
  downloadClaimsReportCsv,
} from '@/hooks/reinsurance/useClaimsReport';
import { todayISODate } from '@/lib/reinsurance/reportDates';

const BUCKET_OPTIONS: { value: ClaimsReportBucket; label: string }[] = [
  { value: 'notification', label: 'Notification' },
  { value: 'open', label: 'Open' },
  { value: 'closed', label: 'Closed' },
];

const STAGE_OPTIONS: { value: string; label: string }[] = [
  { value: 'pending', label: 'Pending' },
  { value: 'finalized', label: 'Finalized' },
];

// Shown only when Stage = Finalized. Buckets a finalized claim by how much of iRisk's
// share has been recovered.
const PAYMENT_STATUS_OPTIONS: { value: string; label: string }[] = [
  { value: 'part', label: 'Part Payment' },
  { value: 'full', label: 'Paid' },
  { value: 'outstanding', label: 'Unpaid' },
];

type ClaimsReportScope = 'general' | 'cedant' | 'reinsurer';

const SCOPE_OPTIONS: { value: ClaimsReportScope; label: string }[] = [
  { value: 'general', label: 'General' },
  { value: 'cedant', label: 'Cedants' },
  { value: 'reinsurer', label: 'Reinsurer' },
];

/* ── formatting ── */

function fmtAmount(value: number | null, currency: string): string {
  if (value == null) return '—';
  return `${currency} ${value.toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function fmtDate(iso: string | null): string {
  if (!iso) return '—';
  return new Date(iso).toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
}

function fmtPeriod(start: string | null, end: string | null): string {
  if (!start && !end) return '—';
  return `${fmtDate(start)} – ${fmtDate(end)}`;
}

function fmtPct(value: number | null): string {
  return value == null ? '—' : `${Number(value)}%`;
}

function fmtInt(value: number | null): string {
  return value == null ? '—' : String(value);
}

/* ── columns ──
 * CSV is generated by the backend with the same filters and row shape. */
type ReportColumn = Column<ClaimReportRow>;

const Muted = ({ children }: { children: React.ReactNode }) => (
  <span className="text-gray-400">{children}</span>
);

const BASE_COLUMNS: ReportColumn[] = [
  {
    key: 'businessName',
    label: 'Business Name',
    width: '130px',
    render: (row) =>
      row.businessName ? (
        <span className="text-gray-700">{row.businessName}</span>
      ) : (
        <Muted>—</Muted>
      ),
  },
  {
    key: 'cedantName',
    label: 'Cedant',
    width: '130px',
    render: (row) => <span className="text-gray-700">{row.cedantName}</span>,
  },
  {
    key: 'policyType',
    label: 'Policy Type',
    width: '120px',
    render: (row) => row.policyType ?? <Muted>—</Muted>,
  },
  {
    key: 'policyNumber',
    label: 'Policy Number',
    width: '130px',
    render: (row) => <EndorsedReferencePill id={row.placementId} reference={row.policyNumber} />,
  },
  {
    key: 'claimType',
    label: 'Claim Type',
    width: '120px',
    render: (row) => row.claimType ?? <Muted>—</Muted>,
  },
  {
    key: 'claimNumber',
    label: 'Claim Number',
    width: '100px',
    render: (row) => <span className="font-medium text-gray-900">{row.claimNumber}</span>,
  },
  {
    key: 'periodOfInsurance',
    label: 'Period of Insurance',
    width: '150px',
    render: (row) => fmtPeriod(row.periodStart, row.periodEnd),
  },
  {
    key: 'dateOfLoss',
    label: 'Date of Loss',
    width: '90px',
    render: (row) => fmtDate(row.occurrenceDate),
  },
  {
    key: 'currency',
    label: 'Currency',
    width: '50px',
    render: (row) => row.currency,
  },
  {
    key: 'claimAmount',
    label: 'Claim Amount',
    width: '130px',
    className: 'text-right',
    render: (row) => fmtAmount(row.claimAmount, row.currency),
  },
];

const IRISK_COLUMNS: ReportColumn[] = [
  {
    key: 'iriskSharePct',
    label: 'iRisk Share %',
    width: '70px',
    className: 'text-right',
    render: (row) => fmtPct(row.iriskSharePercent),
  },
  {
    key: 'iriskShareAmount',
    label: 'iRisk Share Amount',
    width: '130px',
    className: 'text-right',
    render: (row) => fmtAmount(row.iriskShareAmount, row.currency),
  },
  {
    key: 'iriskSharePaid',
    label: 'iRisk Share Paid',
    width: '130px',
    className: 'text-right',
    render: (row) => fmtAmount(row.iriskSharePaid, row.currency),
  },
  {
    key: 'iriskShareOutstanding',
    label: 'iRisk Share Outstanding',
    width: '130px',
    className: 'text-right',
    render: (row) => fmtAmount(row.iriskShareOutstanding, row.currency),
  },
];

// One row per reinsurer on the claim — these columns hold that reinsurer's figures.
// `plural` only switches header wording for the General scope (block sits next to iRisk).
const reinsurerColumns = (plural: boolean): ReportColumn[] => {
  const p = plural ? 'Reinsurer(s)' : 'Reinsurer';
  return [
    {
      key: 'reinsurerName',
      label: `${p} Name`,
      width: '130px',
      render: (row) =>
        row.reinsurerName ? (
          <span className="text-gray-700">{row.reinsurerName}</span>
        ) : (
          <Muted>—</Muted>
        ),
    },
    {
      key: 'reinsurerSharePct',
      label: `${p} % Share`,
      width: '120px',
      className: 'text-right',
      render: (row) => fmtPct(row.reinsurerSharePercent),
    },
    {
      key: 'reinsurerShareAmount',
      label: `${p} Share (Amount)`,
      width: '130px',
      className: 'text-right',
      render: (row) => fmtAmount(row.reinsurerShareAmount, row.currency),
    },
    {
      key: 'reinsurerAmountPaid',
      label: `${p} Amount Paid`,
      width: '130px',
      className: 'text-right',
      render: (row) => fmtAmount(row.reinsurerPaidAmount, row.currency),
    },
    {
      key: 'reinsurerAmountOutstanding',
      label: `${p} Amount Outstanding`,
      width: '150px',
      className: 'text-right',
      render: (row) => fmtAmount(row.reinsurerOutstandingAmount, row.currency),
    },
  ];
};

const AGING_COLUMN: ReportColumn = {
  key: 'agingDays',
  label: 'Aging (days)',
  width: '50px',
  className: 'text-right',
  render: (row) => <span className="text-gray-700">{fmtInt(row.agingDays)}</span>,
};

// Date of loss vs. first premium payment date, in days (negative when the loss
// predates payment).
const DOL_DOP_COLUMN: ReportColumn = {
  key: 'dolDop',
  label: 'DoL:DoP',
  width: '50px',
  className: 'text-right',
  render: (row) => <span className="text-gray-700">{fmtInt(row.dolDop)}</span>,
};

const TAIL_COLUMNS: ReportColumn[] = [AGING_COLUMN, DOL_DOP_COLUMN];

const COLUMNS_BY_SCOPE: Record<ClaimsReportScope, ReportColumn[]> = {
  general: [...BASE_COLUMNS, ...IRISK_COLUMNS, ...reinsurerColumns(true), ...TAIL_COLUMNS],
  cedant: [...BASE_COLUMNS, ...IRISK_COLUMNS, ...TAIL_COLUMNS],
  reinsurer: [...BASE_COLUMNS, ...reinsurerColumns(false), ...TAIL_COLUMNS],
};

export function ClaimsReportTable() {
  const router = useRouter();
  const { tenantSlug } = useParams<{ tenantSlug: string }>();

  // Staged filter values — only applied to the report once "Run Filter" is clicked.
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState(todayISODate());
  const [currencies, setCurrencies] = useState<string[]>([]);
  const [buckets, setBuckets] = useState<string[]>([]);
  const [stages, setStages] = useState<string[]>([]);
  const [paymentStatuses, setPaymentStatuses] = useState<string[]>([]);
  const [scope, setScope] = useState<ClaimsReportScope>('general');
  const [cedantIds, setCedantIds] = useState<string[]>([]);
  const [reinsurerIds, setReinsurerIds] = useState<string[]>([]);
  const [reportParams, setReportParams] = useState<ClaimsReportParams | null>(null);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(50);

  const { options: cedantOptions } = useCedantOptions();
  const { options: reinsurerOptions } = useReinsurerOptions();
  const { data: currencyOptions = [] } = useCurrencyOptions();

  const handleScopeChange = (value: string) => {
    setScope(value as ClaimsReportScope);
    setCedantIds([]);
    setReinsurerIds([]);
    setPage(1);
  };

  const handleStageChange = (next: string[]) => {
    setStages(next);
    if (!next.includes('finalized')) setPaymentStatuses([]);
    setPage(1);
  };

  const { rows, isLoading, meta } = useClaimsReport(reportParams ?? {}, {
    enabled: reportParams !== null,
  });

  const handleRunFilter = () => {
    const nextPage = 1;
    setPage(nextPage);
    setReportParams({
      startDate,
      endDate,
      currencies: currencies.length ? currencies : undefined,
      buckets: buckets.length ? (buckets as ClaimsReportBucket[]) : undefined,
      stages: stages.length ? (stages as Array<'pending' | 'finalized'>) : undefined,
      recoveryStatuses: paymentStatuses.length
        ? (paymentStatuses as Array<'outstanding' | 'part' | 'full'>)
        : undefined,
      scope,
      cedantIds: scope === 'cedant' && cedantIds.length ? cedantIds : undefined,
      reinsurerIds: scope === 'reinsurer' && reinsurerIds.length ? reinsurerIds : undefined,
      page: nextPage,
      limit: pageSize,
    });
  };

  // Column set depends on the selected scope — General shows both the iRisk and
  // reinsurer share blocks, Cedants drops the reinsurer block, Reinsurer drops iRisk.
  const columns = useMemo<ReportColumn[]>(() => COLUMNS_BY_SCOPE[scope], [scope]);

  const rowsPerPageControl =
    reportParams && meta.total > 10 ? (
      <label className="flex items-center gap-1.5 text-sm text-gray-500">
        Rows
        <select
          value={String(pageSize)}
          onChange={(e) => {
            const nextPageSize = Number(e.target.value);
            setPageSize(nextPageSize);
            setPage(1);
            setReportParams((prev) => (prev ? { ...prev, page: 1, limit: nextPageSize } : prev));
          }}
          className="appearance-none rounded-input border border-gray-200 bg-white px-2.5 py-1.5 text-sm text-gray-700 focus:outline-none focus:ring-1 focus:ring-(--focus-ring,var(--color-gray-400))"
        >
          {[10, 20, 50, 100, 200].map((opt) => (
            <option key={String(opt)} value={String(opt)}>
              {opt}
            </option>
          ))}
        </select>
      </label>
    ) : null;

  const handlePageChange = (nextPage: number) => {
    setPage(nextPage);
    setReportParams((prev) => (prev ? { ...prev, page: nextPage, limit: pageSize } : prev));
  };

  const handleExport = async () => {
    if (!reportParams) return;
    const csv = await downloadClaimsReportCsv(reportParams);
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `claims-report-${new Date().toISOString().slice(0, 10)}.csv`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col gap-4 flex-1 min-h-0">
      <div className="flex-1 min-h-0">
        <DataTable
          columns={columns}
          data={rows}
          isLoading={reportParams !== null && isLoading}
          onRowClick={(row) =>
            router.push(
              `/${tenantSlug}/operations/reinsurance/claims/${row.claimId}?placementId=${row.placementId}&tab=${row.bucket}`,
            )
          }
          onExport={reportParams && rows.length > 0 ? handleExport : undefined}
          toolbarTrailing={rowsPerPageControl}
          extraFilters={
            // w-full forces the filter group to own the first toolbar line, so the
            // Export / Run Filter buttons (rendered by DataTable after a flex-1 spacer)
            // always wrap onto a second line and sit flush right at its end.
            <div className="flex w-full items-center gap-2 flex-wrap">
              <div className="w-50">
                <DatePicker
                  size="sm"
                  placeholder="Period start"
                  value={startDate}
                  onChange={setStartDate}
                />
              </div>
              <div className="w-50">
                <DatePicker
                  size="sm"
                  placeholder="Period end"
                  value={endDate}
                  minDate={startDate || undefined}
                  onChange={setEndDate}
                />
              </div>
              <div className="w-32">
                <MultiSelect
                  size="sm"
                  variant="inline"
                  placeholder="Currency"
                  options={currencyOptions}
                  value={currencies}
                  onChange={setCurrencies}
                />
              </div>
              <div className="w-36">
                <MultiSelect
                  size="sm"
                  variant="inline"
                  placeholder="Status"
                  options={BUCKET_OPTIONS}
                  value={buckets}
                  onChange={setBuckets}
                />
              </div>
              <div className="w-36">
                <MultiSelect
                  size="sm"
                  variant="inline"
                  placeholder="Stages"
                  options={STAGE_OPTIONS}
                  value={stages}
                  onChange={handleStageChange}
                />
              </div>
              {stages.includes('finalized') && (
                <div className="w-45">
                  <MultiSelect
                    size="sm"
                    variant="inline"
                    placeholder="Recovery statuses"
                    options={PAYMENT_STATUS_OPTIONS}
                    value={paymentStatuses}
                    onChange={(next) => {
                      setPaymentStatuses(next);
                      setPage(1);
                    }}
                  />
                </div>
              )}
              <div className="w-36">
                <SearchSelect
                  size="sm"
                  disableClear
                  placeholder="Scope"
                  options={SCOPE_OPTIONS}
                  value={scope}
                  onChange={handleScopeChange}
                />
              </div>
              {scope === 'cedant' && (
                <div className="w-44">
                  <MultiSelect
                    size="sm"
                    variant="inline"
                    placeholder="Cedants"
                    options={cedantOptions}
                    value={cedantIds}
                    onChange={setCedantIds}
                  />
                </div>
              )}
              {scope === 'reinsurer' && (
                <div className="w-44">
                  <MultiSelect
                    size="sm"
                    variant="inline"
                    placeholder="Reinsurers"
                    options={reinsurerOptions}
                    value={reinsurerIds}
                    onChange={(next) => {
                      setReinsurerIds(next);
                      setPage(1);
                    }}
                  />
                </div>
              )}
            </div>
          }
          actionButton={{
            label: 'Run Filter',
            onClick: handleRunFilter,
            disabled: !startDate || !endDate,
          }}
          emptyMessage={
            reportParams
              ? 'No claims activity for the selected filters'
              : 'Select a period and click Run Filter to generate the report'
          }
          currentPage={page}
          totalPages={meta.totalPages}
          onPageChange={handlePageChange}
          noInternalScroll
        />
      </div>
    </div>
  );
}
